#!/bin/bash

echo "=== Ensuring Apache2 is installed and running ==="

puppet apply -e "
package { 'apache2':
  ensure => installed,
}

service { 'apache2':
  ensure => running,
  enable => true,
  require => Package['apache2'],
}
"

echo "=== Cleaning up working directory ==="

puppet apply -e "
file { '/tmp/work/3787714v':
  ensure  => absent,
  recurse => true,
  force   => true,
}
"

puppet apply -e "
file { '/tmp/work/3787714v':
  ensure => directory,
  owner  => 'root',
  group  => 'root',
  mode   => '0755',
}
"

echo "=== Cloning Git repository into container ==="

cd /tmp/work/3787714v || exit 1

git clone https://github.com/jeffseet/app-3787714v-repo.git

echo "=== Updating index.html ==="

puppet apply -e "
file { '/var/www/html/index.html':
  ensure  => file,
  source  => '/tmp/work/3787714v/app-3787714v-repo/new_3787714v_index.html',
  owner   => 'root',
  group   => 'root',
  mode    => '0644',
}
"

echo "=== Bolt script execution completed successfully ==="
